name: health_balance
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  go_router: ^12.1.1
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  pie_chart: ^5.4.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
